version: '3'
services:
    mysql:
        image: mysql:5.7
        volumes:
            - ./storage/docker/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'

    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '1025:1025'
            - '8025:8025'
    rabbitmq:
        image: rabbitmq:3-management
        environment:
            RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
            RABBITMQ_DEFAULT_USER: rabbit
            RABBITMQ_DEFAULT_PASS: rabbit
        ports:
            - "15671:15671"
            - "15672:15672"
            - "5671:5671"
            - "5672:5672"
        volumes:
            - ./docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
